# थीम का लफड़ा ही खत्म - अब ये एरर नहीं देगा
theme: jekyll-theme-minimal 

title: "4K AI Wallpapers"
description: "Explore the best 4K AI Wallpapers and backgrounds. Discover a beautiful gallery of high-quality, 100% AI-generated images and informative art for mobile and desktop."
url: "https://4kwax.github.io"
baseurl: ""
timezone: Asia/Kolkata

favicon: "/favicon.png"
future: false
permalink: /:title/

paginate: 15
paginate_path: /page:num/

plugins:
  - jekyll-paginate
  - jekyll-sitemap

theme_config:
  appearance: "dark"
